const awsmobilejsConstant = require('../../../lib/utils/awsmobilejs-constant.js')

describe('awsmobilejs constants', () => {
    test('awsmobilejs constants exist', () => {
        expect(awsmobilejsConstant.AWSMobileJS).toBeDefined()
        expect(awsmobilejsConstant.AWSConfigFileName).toBeDefined()
        expect(awsmobilejsConstant.AWSMobileCLIConfigFileName).toBeDefined()
        expect(awsmobilejsConstant.CustomUserAgent).toBeDefined()
        expect(awsmobilejsConstant.SysDotAWSMobileJSDirName).toBeDefined()
        expect(awsmobilejsConstant.ProjectAWSConfigDirName).toBeDefined()
        expect(awsmobilejsConstant.AWSMobileJSDirName).toBeDefined()
        expect(awsmobilejsConstant.AWSMobileJSBackUpDirName).toBeDefined()
        expect(awsmobilejsConstant.DotAWSMobileSubDirName).toBeDefined()
        expect(awsmobilejsConstant.BackendBuildDirName).toBeDefined()
        expect(awsmobilejsConstant.BackendContentZipFileName).toBeDefined()
        expect(awsmobilejsConstant.InfoDirName).toBeDefined()
        expect(awsmobilejsConstant.AWSInfoFileName).toBeDefined()
        expect(awsmobilejsConstant.ProjectInfoFileName).toBeDefined()
        expect(awsmobilejsConstant.InitInfoFileName).toBeDefined()
        expect(awsmobilejsConstant.ProjectConfigFileName).toBeDefined()
        expect(awsmobilejsConstant.ScriptsDirName).toBeDefined()
        expect(awsmobilejsConstant.ProjectOpsFileName).toBeDefined()
        expect(awsmobilejsConstant.BackendTemplatesDirName).toBeDefined()
        expect(awsmobilejsConstant.ProjectCreationContentZipFileName).toBeDefined()
        expect(awsmobilejsConstant.YmlTempZipFileName).toBeDefined()
        expect(awsmobilejsConstant.ExportJSTempZipFileName).toBeDefined()
        expect(awsmobilejsConstant.YmlExtractTempDirName).toBeDefined()
        expect(awsmobilejsConstant.ExportJSExtractTempDirName).toBeDefined()
        expect(awsmobilejsConstant.CurrentBackendInfoSubDirName).toBeDefined()
        expect(awsmobilejsConstant.BackendDetailsFileName).toBeDefined()
        expect(awsmobilejsConstant.BackendProjectYamlFileName).toBeDefined()
        expect(awsmobilejsConstant.BackendProjectJsonFileName).toBeDefined()
        expect(awsmobilejsConstant.DressedByFeatureFlag).toBeDefined()
        expect(awsmobilejsConstant.AWSExportFileName).toBeDefined()
        expect(awsmobilejsConstant.BackendSubDirName).toBeDefined()
        expect(awsmobilejsConstant.DateTimeFormatString).toBeDefined()
        expect(awsmobilejsConstant.DateTimeFormatStringCompact).toBeDefined()
        expect(awsmobilejsConstant.DefaultAWSAccessKeyId).toBeDefined()
        expect(awsmobilejsConstant.DefaultAWSSecretAccessKey).toBeDefined()
        expect(awsmobilejsConstant.DefaultAWSRegion).toBeDefined()
        expect(awsmobilejsConstant.AWSMobileAPIEndPoint).toBeDefined()
        expect(awsmobilejsConstant.AWSMobileDeviceFarmTestUrl).toBeDefined()
        expect(awsmobilejsConstant.AWSAmazonConsoleUrl).toBeDefined()
        expect(awsmobilejsConstant.AWSEnableMobileRoleUrl).toBeDefined()
        expect(awsmobilejsConstant.AWSCreateIAMUsersUrl).toBeDefined() 
    })
})
